# netlify.toml - build from repo root for NearbyBazaar monorepo
# Builds only the web app and publishes apps/web/.next

[build]
  # Build the web app using pnpm filter so workspaces resolve correctly
  command = "pnpm --filter @nearbybazaar/web build"
  # Publish the Next.js output for the web app
  publish = "apps/web/.next"
  # Ensure Node 18 during build
  environment = { NODE_VERSION = "18" }

# Use Netlify's Next.js plugin to support SSR, ISR, and image optimizations
[[plugins]]
  package = "@netlify/plugin-nextjs"
